version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=*
      - DB_NAME=faucet_db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
      - FAUCET_WALLET_PRIVATE_KEY=${FAUCET_WALLET_PRIVATE_KEY}
      - FAUCET_WALLET_ADDRESS=${FAUCET_WALLET_ADDRESS}
      - FAUCET_AMOUNT=${FAUCET_AMOUNT}
    volumes:
      - .:/app
    networks:
      - faucet-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=faucet_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    networks:
      - faucet-network

volumes:
  postgres_data:

networks:
  faucet-network:
    driver: bridge
